name: Windows (Direct3D12)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Generate Solution
      run: |
        if (Test-Path "armorcore/Kinc/make.js") { 
          node armorcore/Kinc/make -g direct3d12 
        } elseif (Test-Path "Kinc/make.js") { 
          node Kinc/make -g direct3d12 
        } else { 
          node make -g direct3d12 
        }

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile Release Build
      run: |
        msbuild build/ArmorPaint.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Finished Executable
      uses: actions/upload-artifact@v4
      with:
        name: ArmorPaint-Windows
        path: build/x64/Release/
